export interface HawkerDish {
  id: string;
  name_en: string;
  name_local: string;
  aliases: string[];
  category: 'Chinese' | 'Malay' | 'Indian' | 'Western' | 'Drinks' | 'Dim Sum' | 'Peranakan' | 'Snacks';
  stall_type: string;
  portion_default: string;
  portion_grams: number;
  calories: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  sodium_mg: number;
  sugar_g: number;
  fiber_g?: number;
  dietary_flags: Array<'halal' | 'vegetarian' | 'vegan' | 'low_carb' | 'high_protein' | 'healthier_choice' | 'gluten_free'>;
  healthier_alternative: string;
  ordering_tips: string[];
  description: string;
  image_keyword: string;
}

export const HAWKER_DISHES: HawkerDish[] = [
  // ===================== CHINESE HAWKER =====================
  {
    id: 'chicken-rice-steamed',
    name_en: 'Hainanese Steamed Chicken Rice',
    name_local: '白鸡饭 (Bai Ji Fan)',
    aliases: ['chicken rice', 'steamed chicken rice', 'hainanese chicken rice', 'bai ji fan'],
    category: 'Chinese',
    stall_type: 'Chicken Rice Stall',
    portion_default: '1 plate with seasoned rice and cucumber slices',
    portion_grams: 400,
    calories: 607,
    protein_g: 27,
    carbs_g: 65,
    fat_g: 23,
    sodium_mg: 980,
    sugar_g: 2,
    fiber_g: 2,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Request steamed chicken breast without skin, swap half the oily rice for plain white/brown rice, and go easy on dark soy sauce and chili oil.',
    ordering_tips: ['Ask for "ji rou bu yao pi" (no chicken skin)', 'Ask for extra cucumber slices', 'Take light chili sauce instead of excessive ginger oil'],
    description: 'Tender poached chicken served over fragrant rice cooked in chicken broth, ginger, and pandan.',
    image_keyword: 'chicken_rice'
  },
  {
    id: 'chicken-rice-roasted',
    name_en: 'Hainanese Roasted Chicken Rice',
    name_local: '烧鸡饭 (Shao Ji Fan)',
    aliases: ['roast chicken rice', 'roasted chicken rice', 'shao ji fan'],
    category: 'Chinese',
    stall_type: 'Chicken Rice Stall',
    portion_default: '1 plate with roasted chicken and rice',
    portion_grams: 400,
    calories: 630,
    protein_g: 28,
    carbs_g: 66,
    fat_g: 25,
    sodium_mg: 1040,
    sugar_g: 3,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Remove roasted crispy skin to save ~120 kcal and 10g fat; request less gravy poured over rice.',
    ordering_tips: ['Remove skin before eating', 'Dip meat lightly rather than pouring sauce over entire plate'],
    description: 'Crisp, savory roasted chicken served with aromatic seasoned rice and piquant chili sauce.',
    image_keyword: 'roast_chicken_rice'
  },
  {
    id: 'char-kway-teow',
    name_en: 'Char Kway Teow',
    name_local: '炒粿条 (Chao Guo Tiao)',
    aliases: ['char kway teow', 'ckt', 'fried kway teow', 'char kuey teow'],
    category: 'Chinese',
    stall_type: 'Fried Kway Teow Stall',
    portion_default: '1 plate (stir-fried noodles with egg, cockles, lap cheong)',
    portion_grams: 385,
    calories: 745,
    protein_g: 22,
    carbs_g: 76,
    fat_g: 38,
    sodium_mg: 1450,
    sugar_g: 11,
    dietary_flags: [],
    healthier_alternative: 'Ask for "shao you" (less oil), omit lard cubes ("mai bak you") and Chinese sausage (lap cheong), and request extra bean sprouts to cut ~200 kcal.',
    ordering_tips: ['"Mai bak you" (no lard)', '"Shao you" (less oil)', '"Duo dao gei" (more bean sprouts for fiber)'],
    description: 'Flat rice noodles stir-fried in dark soy sauce over high wok hei with cockles, egg, Chinese sausage, and bean sprouts.',
    image_keyword: 'char_kway_teow'
  },
  {
    id: 'laksa-singapore',
    name_en: 'Katong Laksa',
    name_local: '加东叻沙 (Laksa)',
    aliases: ['laksa', 'katong laksa', 'curry laksa', 'singapore laksa'],
    category: 'Peranakan',
    stall_type: 'Laksa Stall',
    portion_default: '1 bowl with thick bee hoon, prawns, cockles, fishcake, tau pok',
    portion_grams: 480,
    calories: 590,
    protein_g: 24,
    carbs_g: 62,
    fat_g: 28,
    sodium_mg: 1580,
    sugar_g: 6,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Do not drink the coconut milk broth completely — drinking only half the broth saves ~180 kcal and over 600mg of sodium! Omit fried tau pok.',
    ordering_tips: ['Enjoy the noodles and seafood, leave the rich coconut broth behind', 'Skip sambal oil on top if watching sodium'],
    description: 'Thick vermicelli in a rich, spicy coconut milk curry broth flavored with dried shrimp and laksa leaves.',
    image_keyword: 'laksa'
  },
  {
    id: 'bak-chor-mee-dry',
    name_en: 'Bak Chor Mee (Dry)',
    name_local: '肉脞面 (干) (Minced Meat Noodles)',
    aliases: ['bak chor mee', 'bcm', 'minced meat noodles dry', 'mee pok tah'],
    category: 'Chinese',
    stall_type: 'Minced Meat Noodle Stall',
    portion_default: '1 bowl mee pok with minced pork, pork liver, meatballs, braised mushrooms',
    portion_grams: 370,
    calories: 510,
    protein_g: 26,
    carbs_g: 64,
    fat_g: 17,
    sodium_mg: 1220,
    sugar_g: 5,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Ask for soup on the side, omit deep-fried lard croutons, and ask for less chili oil and vinegar sauce.',
    ordering_tips: ['"Mai bak you" (no lard)', 'Ask for extra pork slices and lettuce instead of fatty meatballs'],
    description: 'Springy egg noodles tossed in black vinegar and chili paste, topped with stewed mushrooms, minced pork, and pork slices.',
    image_keyword: 'bak_chor_mee'
  },
  {
    id: 'bak-chor-mee-soup',
    name_en: 'Bak Chor Mee (Soup / Bedok Style)',
    name_local: '肉脞面 (汤)',
    aliases: ['bak chor mee soup', 'bcm soup', 'bedok style bcm'],
    category: 'Chinese',
    stall_type: 'Minced Meat Noodle Stall',
    portion_default: '1 bowl soup with noodles and minced pork',
    portion_grams: 450,
    calories: 430,
    protein_g: 24,
    carbs_g: 58,
    fat_g: 11,
    sodium_mg: 1350,
    sugar_g: 2,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Naturally lower in fat than the dry chili-oil tossed version! Avoid drinking all the salty broth to control sodium.',
    ordering_tips: ['Choose bee hoon or mee kia over yellow noodles', 'Do not finish the broth to save ~400mg sodium'],
    description: 'Savory pork broth filled with tender hand-minced pork patties, meatballs, and springy noodles.',
    image_keyword: 'bak_chor_mee_soup'
  },
  {
    id: 'hokkien-mee',
    name_en: 'Fried Hokkien Prawn Mee',
    name_local: '炒福建虾面 (Hokkien Mee)',
    aliases: ['hokkien mee', 'fried hokkien mee', 'singapore hokkien mee', 'fkm'],
    category: 'Chinese',
    stall_type: 'Hokkien Mee Stall',
    portion_default: '1 plate yellow noodles + bee hoon braised in prawn pork broth',
    portion_grams: 410,
    calories: 617,
    protein_g: 25,
    carbs_g: 68,
    fat_g: 27,
    sodium_mg: 1320,
    sugar_g: 4,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Ask for no lard ("mai bak you"), ask for more bee hoon than yellow noodles, and use fresh calamansi lime instead of oily sambal.',
    ordering_tips: ['Squeeze double calamansi lime for bright flavor without added fat', 'Skip crispy pork lard'],
    description: 'Combination of egg noodles and thick vermicelli braised in rich prawn and pork stock with squid, prawns, and egg.',
    image_keyword: 'hokkien_mee'
  },
  {
    id: 'fishball-noodles-soup',
    name_en: 'Fishball Noodles (Soup)',
    name_local: '鱼圆面 (汤) (Yu Yuan Mian)',
    aliases: ['fishball noodles', 'fishball noodle soup', 'mee pok fishball', 'mee kia fishball'],
    category: 'Chinese',
    stall_type: 'Fishball Noodle Stall',
    portion_default: '1 bowl yellow noodles or mee pok with 5-6 fishballs and fishcake',
    portion_grams: 420,
    calories: 380,
    protein_g: 21,
    carbs_g: 56,
    fat_g: 7,
    sodium_mg: 1410,
    sugar_g: 3,
    dietary_flags: ['healthier_choice', 'high_protein'],
    healthier_alternative: 'A classic hawker healthier choice! Choose kway teow or bee hoon over yellow alkaline noodles to reduce sodium, and leave half the soup.',
    ordering_tips: ['Choose bee hoon soup for lower calorie density', 'Ask for extra lettuce/chye sim'],
    description: 'Bouncy, springy fishballs served in a clear comforting broth with noodles, minced meat, and lettuce.',
    image_keyword: 'fishball_noodles'
  },
  {
    id: 'wanton-mee-dry',
    name_en: 'Wanton Mee (Dry)',
    name_local: '云吞面 (干)',
    aliases: ['wanton mee', 'wanton noodles', 'wonton mee dry', 'char siew wanton mee'],
    category: 'Chinese',
    stall_type: 'Wanton Noodle Stall',
    portion_default: '1 plate egg noodles with char siew slices, boiled wantons, and side soup',
    portion_grams: 360,
    calories: 460,
    protein_g: 23,
    carbs_g: 62,
    fat_g: 13,
    sodium_mg: 1190,
    sugar_g: 8,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Choose boiled/soup wantons instead of fried wanton dumplings to cut 100 kcal of deep-fried oil. Request lean char siew ("shou rou").',
    ordering_tips: ['Ask for lean char siew ("shou rou")', 'Skip deep-fried wanton option'],
    description: 'Thin, springy Cantonese egg noodles tossed in savory sauce, topped with honey-roasted pork slices and pork dumplings.',
    image_keyword: 'wanton_mee'
  },
  {
    id: 'ban-mian-soup',
    name_en: 'Ban Mian (Handmade Noodle Soup)',
    name_local: '板面 (汤)',
    aliases: ['ban mian', 'pan mee', 'handmade noodles', 'ban mian soup'],
    category: 'Chinese',
    stall_type: 'Ban Mian / Handmade Noodle Stall',
    portion_default: '1 bowl flat handmade wheat noodles in ikan bilis broth with egg, minced pork, mani cai',
    portion_grams: 480,
    calories: 475,
    protein_g: 27,
    carbs_g: 66,
    fat_g: 11,
    sodium_mg: 1180,
    sugar_g: 2,
    dietary_flags: ['healthier_choice', 'high_protein'],
    healthier_alternative: 'Great balanced meal with fresh greens (mani cai / spinach) and poached egg! Ask for less fried ikan bilis on top to cut sodium.',
    ordering_tips: ['Ask for "duo cai" (extra spinach or mani cai)', 'Hold back on fried shallots and ikan bilis if watching salt'],
    description: 'Comforting hand-kneaded wheat noodles in a sweet anchovy (ikan bilis) broth with minced pork, fresh spinach, and a runny egg.',
    image_keyword: 'ban_mian'
  },
  {
    id: 'carrot-cake-white',
    name_en: 'Fried Carrot Cake (White)',
    name_local: '炒萝卜糕 (白) (Chai Tow Kway White)',
    aliases: ['white carrot cake', 'chai tow kway white', 'fried radish cake white'],
    category: 'Chinese',
    stall_type: 'Carrot Cake Stall',
    portion_default: '1 plate radish rice cake pan-fried with eggs, garlic, and preserved radish (cai po)',
    portion_grams: 340,
    calories: 466,
    protein_g: 14,
    carbs_g: 48,
    fat_g: 24,
    sodium_mg: 1150,
    sugar_g: 3,
    dietary_flags: ['vegetarian'],
    healthier_alternative: 'White carrot cake has less added sugar than black carrot cake (saves ~15g sugar!). Request less oil and less salty preserved radish (cai po).',
    ordering_tips: ['"Shao you" (less oil)', 'Add extra egg for more protein'],
    description: 'Steamed radish and rice flour cubes pan-fried with eggs, garlic, and savory preserved turnip until crisp.',
    image_keyword: 'white_carrot_cake'
  },
  {
    id: 'carrot-cake-black',
    name_en: 'Fried Carrot Cake (Black)',
    name_local: '炒萝卜糕 (黑) (Chai Tow Kway Black)',
    aliases: ['black carrot cake', 'chai tow kway black', 'sweet carrot cake'],
    category: 'Chinese',
    stall_type: 'Carrot Cake Stall',
    portion_default: '1 plate radish cake fried with sweet dark molasses soy sauce and egg',
    portion_grams: 360,
    calories: 566,
    protein_g: 13,
    carbs_g: 72,
    fat_g: 25,
    sodium_mg: 1280,
    sugar_g: 18,
    dietary_flags: ['vegetarian'],
    healthier_alternative: 'Swap to White Carrot Cake to cut 15g of added sugar, or ask for "shao tian jiang" (less sweet sauce).',
    ordering_tips: ['Ask for "shao hei jiang" (less dark sweet sauce)', 'Share a portion with a friend'],
    description: 'Radish cake pan-fried with egg and caramelised sweet black molasses soy sauce.',
    image_keyword: 'black_carrot_cake'
  },
  {
    id: 'popiah-fresh',
    name_en: 'Fresh Popiah (2 rolls)',
    name_local: '薄饼 (Bao Bing)',
    aliases: ['popiah', 'fresh popiah', 'spring roll singapore'],
    category: 'Chinese',
    stall_type: 'Popiah Stall',
    portion_default: '2 fresh rolls with braised jicama, turnip, egg, crushed peanuts',
    portion_grams: 280,
    calories: 376,
    protein_g: 12,
    carbs_g: 48,
    fat_g: 14,
    sodium_mg: 780,
    sugar_g: 8,
    fiber_g: 6,
    dietary_flags: ['healthier_choice', 'vegetarian'],
    healthier_alternative: 'One of the healthiest hawker dishes! Ask for less sweet sauce (tian jiang), no crispy fried batter bits, and extra lettuce.',
    ordering_tips: ['"Mai tian jiang" (no sweet sauce) or "shao tian jiang"', '"Mai cui cui" (no fried crispy bits)'],
    description: 'Thin soft wheat skin wrapped with braised jicama, bean sprouts, crushed peanuts, boiled egg, and coriander.',
    image_keyword: 'popiah'
  },
  {
    id: 'yong-tau-foo-soup',
    name_en: 'Yong Tau Foo (Soup, 6 items + bee hoon)',
    name_local: '酿豆腐 (汤)',
    aliases: ['yong tau foo', 'ytf', 'yong tow foo', 'ytf soup'],
    category: 'Chinese',
    stall_type: 'Yong Tau Foo Stall',
    portion_default: '1 bowl clear soybean broth, 6 non-fried items (tofu, bittergourd, ladyfinger, mushrooms), bee hoon',
    portion_grams: 450,
    calories: 340,
    protein_g: 22,
    carbs_g: 44,
    fat_g: 7,
    sodium_mg: 920,
    sugar_g: 4,
    fiber_g: 5,
    dietary_flags: ['healthier_choice', 'high_protein'],
    healthier_alternative: 'Top recommendation for weight loss and diabetes! Choose fresh bean curd, vegetable-stuffed items, bittergourd, and skip fried beancurd skin (fuzhu).',
    ordering_tips: ['Pick un-fried tofu and fresh vegetables', 'Choose clear broth instead of laksa gravy', 'Dip chili sauce lightly'],
    description: 'Tofu, fresh vegetables, and mushrooms stuffed with lean fish paste served in a light soybean and anchovy broth.',
    image_keyword: 'yong_tau_foo'
  },
  {
    id: 'duck-rice-braised',
    name_en: 'Braised Duck Rice',
    name_local: '卤鸭饭 (Lu Ya Fan)',
    aliases: ['braised duck rice', 'duck rice', 'lu ya fan', 'teochew duck rice'],
    category: 'Chinese',
    stall_type: 'Duck Rice Stall',
    portion_default: '1 plate braised duck with rice and dark herbal gravy',
    portion_grams: 390,
    calories: 620,
    protein_g: 28,
    carbs_g: 64,
    fat_g: 26,
    sodium_mg: 1250,
    sugar_g: 6,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Remove duck skin to eliminate saturated fat; ask for "shao zhi" (less gravy over rice) to slash sodium by ~300mg.',
    ordering_tips: ['Ask for breast meat ("ya xiong")', 'Remove fatty duck skin before eating'],
    description: 'Tender Teochew-style braised duck infused with five-spice powder, star anise, and dark soy, served with herbal rice.',
    image_keyword: 'braised_duck_rice'
  },
  {
    id: 'bak-kut-teh-teochew',
    name_en: 'Bak Kut Teh (Teochew Peppery Pork Rib Soup)',
    name_local: '肉骨茶 (潮州胡椒)',
    aliases: ['bak kut teh', 'bkt', 'pork rib soup', 'teochew bkt'],
    category: 'Chinese',
    stall_type: 'Bak Kut Teh Stall',
    portion_default: '1 bowl peppery pork ribs in clear broth (excluding youtiao/rice)',
    portion_grams: 380,
    calories: 360,
    protein_g: 34,
    carbs_g: 4,
    fat_g: 23,
    sodium_mg: 1180,
    sugar_g: 1,
    dietary_flags: ['low_carb', 'high_protein'],
    healthier_alternative: 'High in protein and virtually zero carb on its own! Skip deep-fried dough fritters (youtiao saves 220 kcal), and pair with plain brown/white rice.',
    ordering_tips: ['Skip the youtiao (fried dough crullers)', 'Pair with blanched chye sim vegetables'],
    description: 'Succulent pork ribs simmered in a peppery, garlic-infused clear broth, served with dark soy and crushed bird’s eye chili.',
    image_keyword: 'bak_kut_teh'
  },
  {
    id: 'fish-head-steamboat',
    name_en: 'Sliced Fish Soup with Bee Hoon',
    name_local: '鱼片米粉汤 (Yu Pian Mi Fen)',
    aliases: ['sliced fish soup', 'fish soup bee hoon', 'sliced fish bee hoon', 'clear fish soup'],
    category: 'Chinese',
    stall_type: 'Fish Soup Stall',
    portion_default: '1 bowl clear broth with fresh sliced batang (Spanish mackerel), tofu, bittergourd, bee hoon',
    portion_grams: 480,
    calories: 355,
    protein_g: 28,
    carbs_g: 48,
    fat_g: 4,
    sodium_mg: 980,
    sugar_g: 2,
    dietary_flags: ['healthier_choice', 'high_protein'],
    healthier_alternative: 'Outstanding everyday healthy meal! Choose fresh sliced fish (not deep-fried fish nuggets) and request no evaporated milk ("mai nai").',
    ordering_tips: ['Specify "mai nai" (no milk) for lower fat', 'Choose sliced fish over fried fish to save 180 kcal'],
    description: 'Delicate fresh mackerel slices simmered in clean fish stock with tomatoes, tofu, and thick vermicelli.',
    image_keyword: 'fish_soup'
  },
  {
    id: 'cai-fan-2veg-1meat',
    name_en: 'Cai Fan / Economical Rice (1 Meat + 2 Veg + Rice)',
    name_local: '杂菜饭 / 经济饭 (Cai Png)',
    aliases: ['cai fan', 'cai png', 'mixed rice', 'economical rice', 'chap chye png'],
    category: 'Chinese',
    stall_type: 'Economical Mixed Rice Stall',
    portion_default: '1 plate white rice, steamed egg / minced pork, stir-fried chye sim, braised cabbage',
    portion_grams: 420,
    calories: 520,
    protein_g: 24,
    carbs_g: 68,
    fat_g: 16,
    sodium_mg: 920,
    sugar_g: 4,
    fiber_g: 4,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Select steamed or stir-fried lean meat (steamed egg with minced pork, stir-fry chicken) and 2 greens. Request brown rice if available, and ask for "mai zhi" (no oily curry/gravy drenched over rice).',
    ordering_tips: ['Choose steamed or braised items over sweet & sour pork or deep-fried chicken cutlet', 'Request "mai zhi" (no gravy drizzled on rice)'],
    description: 'Customizable mixed rice plate with chosen proteins and vegetable dishes.',
    image_keyword: 'cai_fan'
  },
  {
    id: 'cai-fan-unhealthy-combo',
    name_en: 'Cai Fan (Sweet & Sour Pork, Fried Chicken, Curry Gravy)',
    name_local: '杂菜饭 (炸肉/咖喱汁)',
    aliases: ['cai fan fried', 'fried cai png', 'cai fan heavy'],
    category: 'Chinese',
    stall_type: 'Economical Mixed Rice Stall',
    portion_default: '1 plate white rice drenched in curry gravy, sweet & sour pork, deep-fried chicken nugget, stir-fry beans',
    portion_grams: 460,
    calories: 820,
    protein_g: 26,
    carbs_g: 94,
    fat_g: 37,
    sodium_mg: 1680,
    sugar_g: 16,
    dietary_flags: [],
    healthier_alternative: 'Swap sweet & sour pork (heavy cornstarch batter + sugar) for steamed tofu with minced pork or ginger scallion chicken. Cut gravy over rice to save 200 kcal.',
    ordering_tips: ['Pick one green vegetable and one steamed protein instead of two deep-fried dishes'],
    description: 'Heavier mixed rice plate with battered fried meats and rich curry gravy.',
    image_keyword: 'cai_fan_heavy'
  },
  {
    id: 'porridge-century-egg-pork',
    name_en: 'Century Egg & Lean Pork Congee',
    name_local: '皮蛋瘦肉粥 (Pi Dan Shou Rou Zhou)',
    aliases: ['century egg porridge', 'congee', 'pork congee', 'zhou'],
    category: 'Chinese',
    stall_type: 'Congee / Porridge Stall',
    portion_default: '1 bowl Cantonese congee with shredded century egg and lean pork slivers',
    portion_grams: 450,
    calories: 360,
    protein_g: 22,
    carbs_g: 52,
    fat_g: 6,
    sodium_mg: 940,
    sugar_g: 1,
    dietary_flags: ['healthier_choice', 'high_protein'],
    healthier_alternative: 'Easy to digest and low in fat. Omit crispy youtiao fritters to save 120 kcal, and use white pepper instead of extra soy sauce.',
    ordering_tips: ['"Mai youtiao" (no fried dough fritters)', 'Ask for raw egg cracked into hot porridge for extra protein'],
    description: 'Smooth, slow-cooked silky rice porridge simmered with flavorful century egg and tender seasoned lean pork strips.',
    image_keyword: 'congee'
  },

  // ===================== MALAY HAWKER =====================
  {
    id: 'nasi-lemak-set',
    name_en: 'Nasi Lemak with Fried Chicken Wing',
    name_local: 'Nasi Lemak Ayam Goreng',
    aliases: ['nasi lemak', 'coconut rice', 'nasi lemak chicken wing', 'nasi lemak set'],
    category: 'Malay',
    stall_type: 'Nasi Lemak Stall',
    portion_default: '1 plate coconut pandan rice, fried chicken wing, fried ikan bilis, peanuts, cucumber, sambal, fried egg',
    portion_grams: 420,
    calories: 720,
    protein_g: 28,
    carbs_g: 74,
    fat_g: 34,
    sodium_mg: 1280,
    sugar_g: 9,
    dietary_flags: ['halal', 'high_protein'],
    healthier_alternative: 'Ask for grilled fish (ikan kuning / otah) or boiled egg instead of deep-fried chicken wing; ask for a smaller rice portion and moderate the sweet sambal.',
    ordering_tips: ['Swap fried chicken wing for grilled fish or boiled egg to save ~150 kcal', 'Dab sambal on side rather than mixing all into rice'],
    description: 'Fragrant rice steeped in coconut milk and pandan leaf, served with crispy fried chicken wing, sambal, crunchy peanuts, and ikan bilis.',
    image_keyword: 'nasi_lemak'
  },
  {
    id: 'mee-goreng-mamak',
    name_en: 'Mee Goreng (Mamak Fried Noodles)',
    name_local: 'Mee Goreng Mamak',
    aliases: ['mee goreng', 'mamak mee goreng', 'fried noodles mamak', 'indian mee goreng'],
    category: 'Indian',
    stall_type: 'Mamak / Indian-Muslim Stall',
    portion_default: '1 plate yellow noodles fried with mutton/chicken bits, tofu, potato, egg, spicy red paste',
    portion_grams: 400,
    calories: 680,
    protein_g: 22,
    carbs_g: 82,
    fat_g: 28,
    sodium_mg: 1620,
    sugar_g: 8,
    dietary_flags: ['halal'],
    healthier_alternative: 'Ask for "kurang minyak" (less oil), request extra cabbage/bean sprouts, or swap yellow noodles for Bee Hoon Goreng (vermicelli absorbs slightly less oil).',
    ordering_tips: ['"Kurang minyak" (less oil)', 'Squeeze cucumber slices with lime for fresh tang without salt'],
    description: 'Yellow egg noodles wok-tossed with chili, tomato sauce, potatoes, fried tofu cubes, and shredded cabbage.',
    image_keyword: 'mee_goreng'
  },
  {
    id: 'mee-rebus',
    name_en: 'Mee Rebus',
    name_local: 'Mee Rebus',
    aliases: ['mee rebus', 'mie rebus', 'boiled yellow noodles gravy'],
    category: 'Malay',
    stall_type: 'Malay Noodle Stall',
    portion_default: '1 bowl yellow noodles in thick sweet-potato spiced gravy with hard-boiled egg, calamansi, tau pok',
    portion_grams: 460,
    calories: 540,
    protein_g: 20,
    carbs_g: 82,
    fat_g: 14,
    sodium_mg: 1480,
    sugar_g: 15,
    dietary_flags: ['halal'],
    healthier_alternative: 'Gravy is thickened with sweet potato and palm sugar. Eat the noodles and hard-boiled egg, but don’t finish the sweet gravy to lower sugar and carbs by ~25g.',
    ordering_tips: ['Leave 2/3 of the sweet thick gravy', 'Enjoy the boiled egg and tau pok'],
    description: 'Yellow noodles drenched in an aromatic, thick sweet potato and lemongrass gravy garnished with green chili and crushed peanuts.',
    image_keyword: 'mee_rebus'
  },
  {
    id: 'mee-siam',
    name_en: 'Mee Siam (Malay / Nonya Style)',
    name_local: 'Mee Siam',
    aliases: ['mee siam', 'siamese noodles', 'bee hoon mee siam'],
    category: 'Malay',
    stall_type: 'Malay Noodle Stall',
    portion_default: '1 bowl rice vermicelli in sweet, tart, and spicy tamarind gravy with hard-boiled egg and bean sprouts',
    portion_grams: 450,
    calories: 480,
    protein_g: 18,
    carbs_g: 76,
    fat_g: 11,
    sodium_mg: 1540,
    sugar_g: 14,
    dietary_flags: ['halal'],
    healthier_alternative: 'Lower in fat than coconut-based laksa! Because the tamarind gravy has added sugar, enjoy the bee hoon and egg while leaving excess broth behind.',
    ordering_tips: ['Ask for extra chives (kuchai) and bean sprouts for dietary fiber', 'Squeeze calamansi lime for brightness'],
    description: 'Rice vermicelli served in a tangy tamarind, salted soybean, and chili broth, topped with hard-boiled egg, lime, and tau pok.',
    image_keyword: 'mee_siam'
  },
  {
    id: 'soto-ayam',
    name_en: 'Soto Ayam (Malay Chicken Soup with Rice Cakes)',
    name_local: 'Soto Ayam / Lontong Soto',
    aliases: ['soto ayam', 'mee soto', 'lontong soto', 'chicken soto'],
    category: 'Malay',
    stall_type: 'Malay Noodle Stall',
    portion_default: '1 bowl spiced turmeric chicken broth with shredded chicken, bean sprouts, bergedil, lontong',
    portion_grams: 460,
    calories: 410,
    protein_g: 26,
    carbs_g: 52,
    fat_g: 9,
    sodium_mg: 1220,
    sugar_g: 3,
    dietary_flags: ['halal', 'healthier_choice', 'high_protein'],
    healthier_alternative: 'A fantastic, low-fat Malay hawker option! Skip the deep-fried potato patty (bergedil saves ~100 kcal) and ask for extra shredded chicken breast.',
    ordering_tips: ['Skip the bergedil (fried potato cake) to reduce deep-fried fat', 'Ask for extra shredded chicken breast'],
    description: 'Hearty Indonesian-Malay chicken soup infused with turmeric, ginger, and lemongrass, served with shredded chicken and lontong rice cakes.',
    image_keyword: 'soto_ayam'
  },
  {
    id: 'lontong-sayur-lodeh',
    name_en: 'Lontong Sayur Lodeh',
    name_local: 'Lontong Sayur Lodeh',
    aliases: ['lontong', 'sayur lodeh', 'lontong sayur'],
    category: 'Malay',
    stall_type: 'Malay Stall',
    portion_default: '1 bowl compressed rice cakes with vegetable coconut curry (cabbage, long beans, tofu, hard-boiled egg)',
    portion_grams: 480,
    calories: 520,
    protein_g: 17,
    carbs_g: 68,
    fat_g: 20,
    sodium_mg: 1350,
    sugar_g: 9,
    fiber_g: 6,
    dietary_flags: ['halal'],
    healthier_alternative: 'High in vegetable fiber from cabbage and long beans! Cut back on drinking the coconut-vegetable soup base to lower saturated fat.',
    ordering_tips: ['Ask for extra vegetables', 'Leave half the coconut milk gravy in the bowl'],
    description: 'Compressed rice cakes immersed in a fragrant turmeric and coconut vegetable stew with boiled egg and spiced coconut floss (serundeng).',
    image_keyword: 'lontong'
  },
  {
    id: 'satay-chicken-10sticks',
    name_en: 'Chicken Satay (10 sticks with peanut sauce & ketupat)',
    name_local: 'Satay Ayam (10 Cucuk)',
    aliases: ['satay', 'chicken satay', 'satay ayam', 'skewered chicken'],
    category: 'Malay',
    stall_type: 'Satay Stall',
    portion_default: '10 grilled chicken skewers with peanut sauce, cucumber, and 2 ketupat cubes',
    portion_grams: 350,
    calories: 580,
    protein_g: 38,
    carbs_g: 42,
    fat_g: 27,
    sodium_mg: 880,
    sugar_g: 16,
    dietary_flags: ['halal', 'high_protein'],
    healthier_alternative: 'Great high-protein option! The peanut sauce carries the bulk of sugar and calories — dip sparingly rather than drowning the skewers.',
    ordering_tips: ['Dip lightly into peanut sauce', 'Eat plenty of the raw cucumber and onion wedges provided'],
    description: 'Marinated skewers of lemongrass and turmeric chicken charcoal-grilled to perfection, served with sweet-spicy peanut sauce and rice cakes.',
    image_keyword: 'satay'
  },
  {
    id: 'otah-otah',
    name_en: 'Otah-Otah (Muar Style Grilled Fish Cake - 2 pcs)',
    name_local: 'Otah / Otak-Otak',
    aliases: ['otah', 'otak otak', 'grilled fish cake'],
    category: 'Malay',
    stall_type: 'Otah Stall / Hawker Snack',
    portion_default: '2 banana-leaf grilled fish cakes',
    portion_grams: 120,
    calories: 170,
    protein_g: 16,
    carbs_g: 8,
    fat_g: 8,
    sodium_mg: 620,
    sugar_g: 2,
    dietary_flags: ['halal', 'low_carb', 'high_protein', 'healthier_choice'],
    healthier_alternative: 'Excellent high-protein, low-carb snack! Made with minced mackerel fish, chili, lemongrass, and a touch of coconut milk.',
    ordering_tips: ['Great side dish to boost protein without heavy refined carbs'],
    description: 'Spicy ground fish paste mixed with aromatic spices, wrapped in banana leaves and charcoal-grilled.',
    image_keyword: 'otah'
  },
  {
    id: 'nasi-padang-rendang-sayur',
    name_en: 'Nasi Padang (Beef Rendang + Sayur Lodeh + Begedil)',
    name_local: 'Nasi Padang',
    aliases: ['nasi padang', 'beef rendang rice', 'padang rice'],
    category: 'Malay',
    stall_type: 'Nasi Padang Stall',
    portion_default: '1 plate rice with 1 portion beef rendang, curried cabbage, bergedil',
    portion_grams: 450,
    calories: 780,
    protein_g: 36,
    carbs_g: 78,
    fat_g: 34,
    sodium_mg: 1420,
    sugar_g: 7,
    dietary_flags: ['halal', 'high_protein'],
    healthier_alternative: 'Substitute beef rendang for grilled spiced chicken (Ayam Bakar) and swap bergedil for raw ulam (traditional salad) or sambal kangkong.',
    ordering_tips: ['Choose Ayam Bakar (grilled chicken) instead of deep-fried or heavy rendang', 'Ask for sambal belacan on side'],
    description: 'Steamed rice served with rich, slow-simmered caramelized beef rendang and seasoned vegetable sides.',
    image_keyword: 'nasi_padang'
  },

  // ===================== INDIAN / MUSLIM HAWKER =====================
  {
    id: 'roti-prata-plain-2pcs',
    name_en: 'Roti Prata (Plain, 2 pieces with Fish Curry)',
    name_local: 'Roti Prata Kosong (2 keping)',
    aliases: ['roti prata', 'prata', 'roti canai', 'prata kosong'],
    category: 'Indian',
    stall_type: 'Roti Prata Stall',
    portion_default: '2 pieces plain crispy flatbread with small bowl of fish curry',
    portion_grams: 220,
    calories: 440,
    protein_g: 10,
    carbs_g: 54,
    fat_g: 20,
    sodium_mg: 690,
    sugar_g: 3,
    dietary_flags: ['halal', 'vegetarian'],
    healthier_alternative: 'Prata dough is laminated with ghee/margarine. Swap to Thosai (Plain or Masala) to cut fat in half (saves ~180 kcal) and get probiotic fermented lentils!',
    ordering_tips: ['Ask for "kurang minyak" (crispy with less oil)', 'Choose fish curry over mutton curry or sugar'],
    description: 'South Indian layered flatbread fried on a hot griddle until golden and flaky, served with aromatic dhal or fish curry.',
    image_keyword: 'roti_prata'
  },
  {
    id: 'roti-prata-egg',
    name_en: 'Roti Prata with Egg (1 Egg Prata + 1 Plain + Curry)',
    name_local: 'Roti Prata Telur (1 Telur + 1 Kosong)',
    aliases: ['egg prata', 'prata telur', 'roti prata egg'],
    category: 'Indian',
    stall_type: 'Roti Prata Stall',
    portion_default: '1 egg prata + 1 plain prata with fish curry',
    portion_grams: 260,
    calories: 520,
    protein_g: 16,
    carbs_g: 56,
    fat_g: 25,
    sodium_mg: 820,
    sugar_g: 3,
    dietary_flags: ['halal', 'vegetarian'],
    healthier_alternative: 'Egg prata provides higher protein (egg inside). Dip in yellow dhal curry rather than sweet sugar or heavy meat gravies.',
    ordering_tips: ['Pair with plain dhal for lentils and fiber', 'Never dip in granulated sugar'],
    description: 'Flaky griddled flatbread stuffed with egg and onions, served hot with rich curry dipping sauce.',
    image_keyword: 'egg_prata'
  },
  {
    id: 'thosai-masala',
    name_en: 'Masala Thosai (with Sambar & Chutneys)',
    name_local: 'Masala Dosa / Thosai',
    aliases: ['thosai', 'masala thosai', 'masala dosa', 'dosa'],
    category: 'Indian',
    stall_type: 'South Indian Stall',
    portion_default: '1 large crisp fermented crepe stuffed with spiced potato mash, served with sambar and 2 chutneys',
    portion_grams: 320,
    calories: 360,
    protein_g: 10,
    carbs_g: 62,
    fat_g: 8,
    sodium_mg: 860,
    sugar_g: 4,
    fiber_g: 6,
    dietary_flags: ['halal', 'vegetarian', 'healthier_choice'],
    healthier_alternative: 'Much healthier than Roti Prata! Made from naturally fermented rice and black gram (urad dal) batter with minimal oil. High in fiber and gut-friendly.',
    ordering_tips: ['Best hawker breakfast alternative to oily prata', 'Enjoy with lentil sambar and tomato chutney'],
    description: 'Thin, crispy fermented lentil and rice crepe rolled with a spiced potato and onion filling, accompanied by coconut and tomato chutneys.',
    image_keyword: 'thosai'
  },
  {
    id: 'thosai-plain',
    name_en: 'Plain Thosai (2 pieces with Sambar)',
    name_local: 'Plain Thosai / Dosa',
    aliases: ['plain thosai', 'thosai kosong', 'plain dosa'],
    category: 'Indian',
    stall_type: 'South Indian Stall',
    portion_default: '2 plain thosai with dhal sambar and coconut chutney',
    portion_grams: 240,
    calories: 270,
    protein_g: 8,
    carbs_g: 50,
    fat_g: 4,
    sodium_mg: 640,
    sugar_g: 2,
    fiber_g: 4,
    dietary_flags: ['halal', 'vegetarian', 'vegan', 'healthier_choice'],
    healthier_alternative: 'One of the lowest calorie, lowest fat hawker breakfast meals in Singapore (~270 kcal).',
    ordering_tips: ['Load up on lentil sambar for vegetable protein', 'Go light on coconut chutney'],
    description: 'Light, golden fermented savory crepes served with nourishing lentil vegetable curry.',
    image_keyword: 'plain_thosai'
  },
  {
    id: 'briyani-chicken',
    name_en: 'Chicken Briyani (Dum Briyani with Achar & Curry)',
    name_local: 'Nasi Briyani Ayam',
    aliases: ['chicken briyani', 'briyani', 'nasi biryani', 'nasi briyani chicken'],
    category: 'Indian',
    stall_type: 'Briyani Stall',
    portion_default: '1 plate spiced basmati rice with whole chicken thigh, dalcha, cucumber acar',
    portion_grams: 480,
    calories: 790,
    protein_g: 42,
    carbs_g: 88,
    fat_g: 29,
    sodium_mg: 1380,
    sugar_g: 5,
    dietary_flags: ['halal', 'high_protein'],
    healthier_alternative: 'High in protein (42g) from whole chicken portion! Eat 2/3 of the basmati rice portion (saves ~180 kcal) and omit excess chicken skin.',
    ordering_tips: ['Leave some of the ghee-flavored basmati rice', 'Eat all the pickled cucumber acar to aid digestion'],
    description: 'Long-grain basmati rice fragrant with saffron, cardamom, and clove, served with spiced bone-in chicken and lentil dalcha.',
    image_keyword: 'chicken_briyani'
  },
  {
    id: 'briyani-mutton',
    name_en: 'Mutton Briyani',
    name_local: 'Nasi Briyani Kambing',
    aliases: ['mutton briyani', 'lamb briyani', 'kambing briyani'],
    category: 'Indian',
    stall_type: 'Briyani Stall',
    portion_default: '1 plate basmati rice with tender spiced mutton shank and dalcha',
    portion_grams: 490,
    calories: 860,
    protein_g: 45,
    carbs_g: 88,
    fat_g: 36,
    sodium_mg: 1460,
    sugar_g: 4,
    dietary_flags: ['halal', 'high_protein'],
    healthier_alternative: 'Rich in iron and protein. Split the large rice portion with a dining partner and request more vegetable dalcha.',
    ordering_tips: ['Trim visible fat from mutton pieces', 'Share the rice mound with someone'],
    description: 'Savory braised mutton layered with spiced saffron basmati rice, crispy fried shallots, and spicy gravy.',
    image_keyword: 'mutton_briyani'
  },
  {
    id: 'murtabak-chicken',
    name_en: 'Chicken Murtabak (with Curry)',
    name_local: 'Murtabak Ayam',
    aliases: ['murtabak', 'chicken murtabak', 'roti murtabak'],
    category: 'Indian',
    stall_type: 'Roti Prata / Mamak Stall',
    portion_default: '1 medium rectangular stuffed folded prata with spiced minced chicken, egg, onions',
    portion_grams: 380,
    calories: 680,
    protein_g: 34,
    carbs_g: 62,
    fat_g: 31,
    sodium_mg: 1240,
    sugar_g: 4,
    dietary_flags: ['halal', 'high_protein'],
    healthier_alternative: 'Packed with protein from egg and chicken mince! Order to share among 2 people or request less oil on the flat-top griddle.',
    ordering_tips: ['Share half a portion with a friend', 'Pair with dhal rather than sweet curry'],
    description: 'Pan-fried folded dough envelope stuffed generously with seasoned minced chicken, beaten egg, garlic, and sliced red onions.',
    image_keyword: 'murtabak'
  },
  {
    id: 'roti-john',
    name_en: 'Roti John (Malay-Indian Omelette Baguette)',
    name_local: 'Roti John',
    aliases: ['roti john', 'egg sandwich mamak'],
    category: 'Malay',
    stall_type: 'Malay-Indian Stall',
    portion_default: 'Half French loaf pan-fried with spiced minced meat and egg, drizzled with chili sauce and mayo',
    portion_grams: 300,
    calories: 580,
    protein_g: 26,
    carbs_g: 58,
    fat_g: 27,
    sodium_mg: 1190,
    sugar_g: 9,
    dietary_flags: ['halal', 'high_protein'],
    healthier_alternative: 'Ask for "kurang mayo dan sos" (less mayonnaise and sweet chili sauce) to cut ~120 kcal and 12g fat immediately.',
    ordering_tips: ['"Kurang sos dan mayo" (easy on the sauces)', 'Request extra cucumber shreds'],
    description: 'Crusty local baguette pan-fried face down with beaten eggs, minced meat, and onions, topped with sauces.',
    image_keyword: 'roti_john'
  },
  {
    id: 'vadai-masala-2pcs',
    name_en: 'Masala Vadai (2 pieces)',
    name_local: 'Masala Vadai / Paruppu Vadai',
    aliases: ['vadai', 'masala vadai', 'lentil fritter'],
    category: 'Indian',
    stall_type: 'Indian Snack Stall',
    portion_default: '2 deep-fried chana dal fritters with curry leaves and fennel',
    portion_grams: 130,
    calories: 290,
    protein_g: 9,
    carbs_g: 32,
    fat_g: 14,
    sodium_mg: 480,
    sugar_g: 1,
    fiber_g: 5,
    dietary_flags: ['halal', 'vegetarian', 'vegan'],
    healthier_alternative: 'High in dietary fiber from whole split yellow chickpeas. Blot excess surface oil with a napkin before eating.',
    ordering_tips: ['Dab oil with tissue before eating', 'Good plant-based protein snack'],
    description: 'Crunchy deep-fried spiced chickpea patties infused with crushed fennel seeds, onion, green chili, and fragrant curry leaves.',
    image_keyword: 'masala_vadai'
  },

  // ===================== WESTERN HAWKER =====================
  {
    id: 'chicken-chop-black-pepper',
    name_en: 'Hawker Chicken Chop (with Fries & Coleslaw)',
    name_local: '西餐鸡扒 (Chicken Chop)',
    aliases: ['chicken chop', 'black pepper chicken chop', 'hawker western chicken chop'],
    category: 'Western',
    stall_type: 'Western Food Stall',
    portion_default: '1 grilled boneless chicken thigh with black pepper sauce, crinkle-cut fries, coleslaw, bun',
    portion_grams: 450,
    calories: 740,
    protein_g: 44,
    carbs_g: 52,
    fat_g: 38,
    sodium_mg: 1360,
    sugar_g: 11,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Ask to swap deep-fried French fries for a baked potato or extra garden salad; request black pepper sauce on the side.',
    ordering_tips: ['"Sauce on the side"', 'Swap fries for baked potato or extra salad if available'],
    description: 'Sizzling grilled chicken thigh served with pungent black pepper gravy, French fries, and sweet coleslaw.',
    image_keyword: 'chicken_chop'
  },
  {
    id: 'fish-and-chips-hawker',
    name_en: 'Hawker Fish and Chips (Deep Fried Dory)',
    name_local: '炸鱼条 (Fish and Chips)',
    aliases: ['fish and chips', 'fried fish western', 'dory fish and chips'],
    category: 'Western',
    stall_type: 'Western Food Stall',
    portion_default: '1 battered deep-fried fish fillet with French fries and tartar sauce',
    portion_grams: 420,
    calories: 820,
    protein_g: 32,
    carbs_g: 74,
    fat_g: 43,
    sodium_mg: 1220,
    sugar_g: 6,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Request grilled fish instead of deep-fried battered fish — cuts ~280 kcal and 25g fat instantly!',
    ordering_tips: ['Order "Grilled Fish" instead of deep-fried', 'Go easy on the mayo-based tartar sauce'],
    description: 'Golden-battered white fish fillet fried crisp, served with thick potato fries and tartar dipping sauce.',
    image_keyword: 'fish_and_chips'
  },
  {
    id: 'grilled-fish-western',
    name_en: 'Grilled Fish with Baked Potato & Salad',
    name_local: '烤鱼扒 (Grilled Fish)',
    aliases: ['grilled fish', 'grilled fish western', 'healthy western fish'],
    category: 'Western',
    stall_type: 'Western Food Stall',
    portion_default: '1 grilled dory fillet with herb butter, baked potato with sour cream, garden salad',
    portion_grams: 400,
    calories: 460,
    protein_g: 36,
    carbs_g: 38,
    fat_g: 17,
    sodium_mg: 820,
    sugar_g: 4,
    dietary_flags: ['healthier_choice', 'high_protein'],
    healthier_alternative: 'The gold standard healthy choice at Western hawker stalls! High lean protein, baked complex carb, and light vegetable greens.',
    ordering_tips: ['Ask for butter/sour cream on the side for the potato', 'Choose garlic herb sauce over heavy cream'],
    description: 'Tender grilled fish fillet seasoned with herbs, served with a fluffy baked potato and crisp side salad.',
    image_keyword: 'grilled_fish'
  },

  // ===================== DIM SUM & KOPITIAM BREAKFAST =====================
  {
    id: 'kaya-toast-set',
    name_en: 'Traditional Kaya Butter Toast Set (2 slices + 2 eggs + Kopi)',
    name_local: '咖椰面包及半生熟蛋套餐',
    aliases: ['kaya toast', 'kaya toast set', 'half boiled eggs', 'kaya butter toast'],
    category: 'Chinese',
    stall_type: 'Kopitiam / Drink Stall',
    portion_default: '2 slices toasted bread with coconut pandan kaya & butter, 2 soft-boiled eggs with soy sauce and pepper',
    portion_grams: 280,
    calories: 450,
    protein_g: 16,
    carbs_g: 52,
    fat_g: 19,
    sodium_mg: 580,
    sugar_g: 18,
    dietary_flags: ['vegetarian', 'high_protein'],
    healthier_alternative: 'Ask for "shao you" (less butter) or scrape off excess butter slab to save 80 kcal of saturated fat. Drink Kopi-O Kosong (0 sugar).',
    ordering_tips: ['Dip toast into protein-rich soft-boiled eggs', 'Ask for thin butter spread'],
    description: 'Crisp charcoal-grilled white toast slathered with sweet coconut pandan jam and chilled butter, paired with runny soft-boiled eggs.',
    image_keyword: 'kaya_toast'
  },
  {
    id: 'soft-boiled-eggs-2pcs',
    name_en: 'Soft-Boiled Eggs (2 eggs)',
    name_local: '半生熟鸡蛋 (2粒)',
    aliases: ['soft boiled eggs', 'half boiled eggs', 'kopitiam eggs'],
    category: 'Chinese',
    stall_type: 'Kopitiam / Drink Stall',
    portion_default: '2 warm eggs in shell served with dark soy sauce and white pepper',
    portion_grams: 110,
    calories: 144,
    protein_g: 13,
    carbs_g: 1,
    fat_g: 10,
    sodium_mg: 280,
    sugar_g: 0,
    dietary_flags: ['healthier_choice', 'low_carb', 'high_protein', 'vegetarian', 'gluten_free'],
    healthier_alternative: 'Pure, nutrient-dense breakfast staple rich in choline and bioavailable protein. Don’t drown in dark sweet soy sauce.',
    ordering_tips: ['Add generous white pepper and just a couple drops of dark soy sauce'],
    description: 'Perfect runny poached-in-shell eggs ready to be cracked into a saucer and seasoned with dark soy.',
    image_keyword: 'soft_boiled_eggs'
  },
  {
    id: 'siew-mai-3pcs',
    name_en: 'Siew Mai (Pork & Prawn Dumplings - 3 pcs)',
    name_local: '烧卖 (3粒)',
    aliases: ['siew mai', 'siu mai', 'shu mai', 'pork dumpling dim sum'],
    category: 'Dim Sum',
    stall_type: 'Dim Sum Stall',
    portion_default: '3 steamed dumplings in bamboo steamer',
    portion_grams: 105,
    calories: 185,
    protein_g: 11,
    carbs_g: 12,
    fat_g: 10,
    sodium_mg: 520,
    sugar_g: 2,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Steamed rather than deep-fried! Good compact protein source; watch portion count as sodium accumulates.',
    ordering_tips: ['Dip lightly into chili sauce without soaking'],
    description: 'Open-topped steamed yellow wonton pastry cups filled with juicy minced pork, shrimp, and shiitake mushrooms.',
    image_keyword: 'siew_mai'
  },
  {
    id: 'har-gao-3pcs',
    name_en: 'Har Gao (Steamed Prawn Dumplings - 3 pcs)',
    name_local: '虾饺 (3粒)',
    aliases: ['har gao', 'ha gao', 'steamed prawn dumpling', 'crystal shrimp dumpling'],
    category: 'Dim Sum',
    stall_type: 'Dim Sum Stall',
    portion_default: '3 translucent steamed dumplings with whole shrimp filling',
    portion_grams: 95,
    calories: 145,
    protein_g: 9,
    carbs_g: 18,
    fat_g: 4,
    sodium_mg: 410,
    sugar_g: 1,
    dietary_flags: ['healthier_choice', 'high_protein'],
    healthier_alternative: 'Leaner than pork siew mai! The translucent tapioca-wheat skin encloses pure fresh shrimp with very little fat.',
    ordering_tips: ['Excellent lower-fat dim sum choice'],
    description: 'Delicate translucent pleated dumplings encasing succulent whole prawns.',
    image_keyword: 'har_gao'
  },
  {
    id: 'char-siew-bao-1pc',
    name_en: 'Char Siew Bao (Steamed BBQ Pork Bun - 1 pc)',
    name_local: '叉烧包 (1粒)',
    aliases: ['char siew bao', 'bbq pork bun', 'steamed pork bun', 'bao'],
    category: 'Dim Sum',
    stall_type: 'Bao / Dim Sum Stall',
    portion_default: '1 fluffy steamed yeast bun with sweet roasted pork filling',
    portion_grams: 90,
    calories: 220,
    protein_g: 8,
    carbs_g: 34,
    fat_g: 6,
    sodium_mg: 380,
    sugar_g: 10,
    dietary_flags: [],
    healthier_alternative: 'Satisfying snack, but the BBQ sauce has significant sugar. Enjoy 1 piece and pair with unsweetened Chinese tea.',
    ordering_tips: ['Pair with hot Chinese tea to balance sweetness'],
    description: 'Fluffy, cloud-like split steamed bun concealing sticky sweet caramelized barbecue pork.',
    image_keyword: 'char_siew_bao'
  },
  {
    id: 'chee-cheong-fun-plain',
    name_en: 'Chee Cheong Fun (Plain with Sweet Sauce & Sesame)',
    name_local: '猪肠粉 (甜酱)',
    aliases: ['chee cheong fun', 'rice noodle roll', 'ccf'],
    category: 'Chinese',
    stall_type: 'Chee Cheong Fun Stall',
    portion_default: '2 rolled steamed rice sheets snipped and dressed with sweet brown sauce, chili, and toasted sesame',
    portion_grams: 220,
    calories: 290,
    protein_g: 4,
    carbs_g: 58,
    fat_g: 5,
    sodium_mg: 820,
    sugar_g: 12,
    dietary_flags: ['vegetarian', 'vegan'],
    healthier_alternative: 'Ask for Hong Kong style Chee Cheong Fun with fresh prawns (higher protein) and light seasoned soy sauce instead of the sugary red/brown sweet paste.',
    ordering_tips: ['Ask for light soy sauce instead of heavy dark sweet sauce', 'Add fresh prawns for protein'],
    description: 'Silky steamed rolled rice noodle sheets drizzled with sweet bean paste sauce, chili oil, and sesame seeds.',
    image_keyword: 'chee_cheong_fun'
  },

  // ===================== SNACKS & SWEETS =====================
  {
    id: 'rojak-singapore',
    name_en: 'Singapore Chinese Rojak',
    name_local: '新加坡罗惹 (Rojak)',
    aliases: ['rojak', 'chinese rojak', 'fruit rojak'],
    category: 'Chinese',
    stall_type: 'Rojak Stall',
    portion_default: '1 plate pineapples, cucumber, turnip, youtiao, tau pok tossed in fermented shrimp paste & peanuts',
    portion_grams: 320,
    calories: 440,
    protein_g: 10,
    carbs_g: 64,
    fat_g: 16,
    sodium_mg: 950,
    sugar_g: 28,
    fiber_g: 5,
    dietary_flags: ['vegetarian'],
    healthier_alternative: 'Ask for "mai youtiao" (no fried dough fritters) and extra fresh cucumber and pineapple; ask for less sweet hay ko (black prawn paste dressing).',
    ordering_tips: ['Ask for extra cucumber and turnip', 'Request "shao jiang" (less sweet shrimp paste)'],
    description: 'Rustic salad of tropical fruits and crisp fritters tossed in pungent fermented prawn paste, tamarind, chili, and toasted peanuts.',
    image_keyword: 'rojak'
  },
  {
    id: 'curry-puff-potato',
    name_en: 'Curry Puff (Potato & Egg)',
    name_local: '咖喱角 (Curry Puff)',
    aliases: ['curry puff', 'karipap', 'epok epok'],
    category: 'Snacks',
    stall_type: 'Halal Snack Stall / Hawker Bakery',
    portion_default: '1 deep-fried shortcrust pastry filled with curried potatoes and hard-boiled egg',
    portion_grams: 115,
    calories: 330,
    protein_g: 6,
    carbs_g: 38,
    fat_g: 17,
    sodium_mg: 490,
    sugar_g: 3,
    dietary_flags: ['halal', 'vegetarian'],
    healthier_alternative: 'Choose baked curry puff if available, or split with a friend since deep-fried pastry has high palm oil content.',
    ordering_tips: ['Eat as an occasional treat rather than daily breakfast'],
    description: 'Deep-fried hand-pinched pastry shell bulging with spicy turmeric potato cubes and a quarter hard-boiled egg.',
    image_keyword: 'curry_puff'
  },
  {
    id: 'tau-huay-sugar',
    name_en: 'Beancurd / Tau Huay (Warm with Sugar Syrup)',
    name_local: '豆腐花 (豆花)',
    aliases: ['tau huay', 'douhua', 'soy beancurd', 'beancurd pudding'],
    category: 'Snacks',
    stall_type: 'Soy Milk / Beancurd Stall',
    portion_default: '1 bowl silky warm soybean curd in light sugar syrup',
    portion_grams: 260,
    calories: 160,
    protein_g: 7,
    carbs_g: 27,
    fat_g: 3,
    sodium_mg: 40,
    sugar_g: 22,
    dietary_flags: ['healthier_choice', 'vegetarian', 'vegan'],
    healthier_alternative: 'Ask for "shao tang" (less sugar syrup) or "mai tang" (no syrup) to cut sugar to <4g while enjoying clean plant protein and calcium!',
    ordering_tips: ['"Shao tang" (half syrup)', '"Mai tang" (unsweetened, naturally sweet soy flavor)'],
    description: 'Silken, delicate soybean curd that melts on the tongue, gently sweetened with pandan-infused sugar syrup.',
    image_keyword: 'tau_huay'
  },

  // ===================== KOPITIAM DRINKS (CRITICAL SEEDING) =====================
  {
    id: 'kopi',
    name_en: 'Kopi (Coffee with Condensed Milk & Evaporated Milk)',
    name_local: '咖啡 (Kopi Regular)',
    aliases: ['kopi', 'coffee condensed milk', 'traditional kopi'],
    category: 'Drinks',
    stall_type: 'Kopitiam Drink Stall',
    portion_default: '1 cup (220ml)',
    portion_grams: 220,
    calories: 135,
    protein_g: 3,
    carbs_g: 22,
    fat_g: 4,
    sodium_mg: 60,
    sugar_g: 20,
    dietary_flags: ['vegetarian'],
    healthier_alternative: 'Order "Kopi Siu Dai" (less condensed milk, ~11g sugar) or switch to "Kopi-O Kosong" (0g sugar, only 5 calories!).',
    ordering_tips: ['Ask for "Kopi Siu Dai" to cut sugar by half', 'Order "Kopi-C Siu Dai" for fresh unsweetened milk + less sugar'],
    description: 'Robusta coffee beans roasted with butter and sugar, strained through a sock filter, and mixed with sweet condensed milk.',
    image_keyword: 'kopi'
  },
  {
    id: 'kopi-siu-dai',
    name_en: 'Kopi Siu Dai (Coffee with Less Sweet Condensed Milk)',
    name_local: '咖啡少甜 (Kopi Siew Dai)',
    aliases: ['kopi siu dai', 'kopi siew dai', 'kopi less sweet'],
    category: 'Drinks',
    stall_type: 'Kopitiam Drink Stall',
    portion_default: '1 cup (220ml)',
    portion_grams: 220,
    calories: 90,
    protein_g: 2,
    carbs_g: 14,
    fat_g: 3,
    sodium_mg: 45,
    sugar_g: 11,
    dietary_flags: ['healthier_choice', 'vegetarian'],
    healthier_alternative: 'The most popular daily healthier upgrade in Singapore! Halves the sugar intake while keeping that creamy richness.',
    ordering_tips: ['"Kopi Siu Dai" cuts sugar by ~45% compared to regular Kopi'],
    description: 'Singapore traditional sock-brewed coffee prepared with less condensed milk for a stronger coffee roast and subtle sweetness.',
    image_keyword: 'kopi_siu_dai'
  },
  {
    id: 'kopi-o-kosong',
    name_en: 'Kopi-O Kosong (Black Coffee, No Sugar, No Milk)',
    name_local: '咖啡乌无糖 (Kopi-O Kosong)',
    aliases: ['kopi o kosong', 'kopi-o kosong', 'black coffee no sugar', 'kosong'],
    category: 'Drinks',
    stall_type: 'Kopitiam Drink Stall',
    portion_default: '1 cup (220ml)',
    portion_grams: 220,
    calories: 5,
    protein_g: 1,
    carbs_g: 1,
    fat_g: 0,
    sodium_mg: 10,
    sugar_g: 0,
    dietary_flags: ['healthier_choice', 'low_carb', 'vegan', 'vegetarian'],
    healthier_alternative: 'Ultimate zero-calorie champion! Zero sugar, zero saturated fat, pure rich aroma with natural antioxidants.',
    ordering_tips: ['Pronounced "Koh-pee Oh Koh-song"', 'Best companion for weight loss and blood sugar management'],
    description: 'Pure, aromatic dark-roasted sock coffee served black without any sugar or condensed milk.',
    image_keyword: 'kopi_o_kosong'
  },
  {
    id: 'kopi-c-siu-dai',
    name_en: 'Kopi-C Siu Dai (Coffee with Evaporated Milk & Less Sugar)',
    name_local: '咖啡C少甜 (Kopi C Siew Dai)',
    aliases: ['kopi c siu dai', 'kopi-c siew dai', 'kopi c less sugar'],
    category: 'Drinks',
    stall_type: 'Kopitiam Drink Stall',
    portion_default: '1 cup (220ml)',
    portion_grams: 220,
    calories: 75,
    protein_g: 2,
    carbs_g: 10,
    fat_g: 3,
    sodium_mg: 45,
    sugar_g: 7,
    dietary_flags: ['healthier_choice', 'vegetarian'],
    healthier_alternative: 'Evaporated milk has no added sugar (unlike condensed milk). Adding just half a teaspoon of sugar gives a balanced, velvety brew.',
    ordering_tips: ['Great choice if you enjoy creamy texture without excessive condensed sugar'],
    description: 'Traditional coffee topped with unsweetened evaporated milk and a modest pinch of sugar.',
    image_keyword: 'kopi_c'
  },
  {
    id: 'teh',
    name_en: 'Teh (Milk Tea with Condensed Milk)',
    name_local: '茶 (Teh Regular)',
    aliases: ['teh', 'tea condensed milk', 'singapore milk tea'],
    category: 'Drinks',
    stall_type: 'Kopitiam Drink Stall',
    portion_default: '1 cup (220ml)',
    portion_grams: 220,
    calories: 140,
    protein_g: 3,
    carbs_g: 23,
    fat_g: 4,
    sodium_mg: 65,
    sugar_g: 21,
    dietary_flags: ['vegetarian'],
    healthier_alternative: 'Order "Teh Siu Dai" (saves ~10g sugar) or "Teh-O Kosong" (0g sugar).',
    ordering_tips: ['Ask for "Teh Siu Dai"', 'Try "Teh-C Kosong" for unsweetened creamy Ceylon tea'],
    description: 'Ceylon black tea brewed strong, sweetened with condensed and evaporated milk.',
    image_keyword: 'teh'
  },
  {
    id: 'teh-o-kosong',
    name_en: 'Teh-O Kosong (Pure Black Tea, No Sugar)',
    name_local: '茶乌无糖 (Teh-O Kosong)',
    aliases: ['teh o kosong', 'teh-o kosong', 'black tea no sugar'],
    category: 'Drinks',
    stall_type: 'Kopitiam Drink Stall',
    portion_default: '1 cup (220ml)',
    portion_grams: 220,
    calories: 2,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 0,
    sodium_mg: 5,
    sugar_g: 0,
    dietary_flags: ['healthier_choice', 'low_carb', 'vegan', 'vegetarian'],
    healthier_alternative: 'Zero calories! Loaded with black tea theaflavins and catechins. Perfect cleansing drink after an oily meal.',
    ordering_tips: ['Add a squeeze of calamansi lime for "Teh-O Limau Kosong" (refreshing zero-sugar citrus tea)'],
    description: 'Strong steeped red Ceylon tea served hot without added milk or sugar.',
    image_keyword: 'teh_o_kosong'
  },
  {
    id: 'teh-tarik',
    name_en: 'Teh Tarik (Pulled Frothy Milk Tea)',
    name_local: 'Teh Tarik',
    aliases: ['teh tarik', 'pulled tea', 'mamak teh tarik'],
    category: 'Drinks',
    stall_type: 'Mamak / Indian-Muslim Stall',
    portion_default: '1 glass pulled with frothy crest (250ml)',
    portion_grams: 250,
    calories: 165,
    protein_g: 4,
    carbs_g: 26,
    fat_g: 5,
    sodium_mg: 80,
    sugar_g: 24,
    dietary_flags: ['halal', 'vegetarian'],
    healthier_alternative: 'Order "Teh Tarik Kurang Manis" to ask the tea master to pull with half condensed milk (cuts 11g sugar).',
    ordering_tips: ['"Teh Tarik Kurang Manis" (less sweet pulled tea)'],
    description: 'Black tea and sweet condensed milk expertly pulled through the air between two vessels to create a silky, frothy head.',
    image_keyword: 'teh_tarik'
  },
  {
    id: 'sugarcane-juice-lemon',
    name_en: 'Fresh Sugarcane Juice with Lemon',
    name_local: '甘蔗水 (加柠檬)',
    aliases: ['sugarcane juice', 'fresh sugarcane', 'sugarcane lemon'],
    category: 'Drinks',
    stall_type: 'Fruit Juice Stall',
    portion_default: '1 large mug freshly pressed with ice (400ml)',
    portion_grams: 400,
    calories: 180,
    protein_g: 1,
    carbs_g: 44,
    fat_g: 0,
    sodium_mg: 25,
    sugar_g: 40,
    dietary_flags: ['vegan', 'vegetarian'],
    healthier_alternative: 'Natural sugarcane has a very high glycemic load (~40g sucrose/fructose). Drink occasionally or share with a friend. Swap to fresh coconut water or barley water for lower glycemic impact.',
    ordering_tips: ['Add lemon for citric acidity and refreshing balance', 'Share large cup with friend'],
    description: 'Fresh stalk sugarcane crushed through roller presses over crushed ice with a squeeze of fresh lemon juice.',
    image_keyword: 'sugarcane_juice'
  },
  {
    id: 'barley-water-homemade',
    name_en: 'Homemade Barley Water (Shao Tang / Less Sweet)',
    name_local: '薏米水 (少糖)',
    aliases: ['barley water', 'homemade barley', 'yi mi shui'],
    category: 'Drinks',
    stall_type: 'Drink Stall',
    portion_default: '1 cup boiled pearl barley water with grains (300ml)',
    portion_grams: 300,
    calories: 95,
    protein_g: 2,
    carbs_g: 22,
    fat_g: 0,
    sodium_mg: 15,
    sugar_g: 10,
    fiber_g: 3,
    dietary_flags: ['healthier_choice', 'vegetarian', 'vegan'],
    healthier_alternative: 'Traditional cooling tonic! Ask for "shao tang" (less sugar) and eat the boiled pearl barley grains at the bottom for soluble beta-glucan fiber.',
    ordering_tips: ['Eat the barley grains for healthy soluble fiber', 'Ask for homemade rather than canned barley'],
    description: 'Gentle, comforting simmered pearl barley drink infused with pandan leaves and light candied winter melon.',
    image_keyword: 'barley_water'
  },
  {
    id: 'bandung',
    name_en: 'Sirap Bandung (Rose Syrup with Condensed Milk)',
    name_local: 'Air Bandung',
    aliases: ['bandung', 'sirap bandung', 'rose syrup milk'],
    category: 'Drinks',
    stall_type: 'Malay / Drink Stall',
    portion_default: '1 glass bright pink iced rose syrup drink (300ml)',
    portion_grams: 300,
    calories: 220,
    protein_g: 3,
    carbs_g: 38,
    fat_g: 6,
    sodium_mg: 90,
    sugar_g: 36,
    dietary_flags: ['halal', 'vegetarian'],
    healthier_alternative: 'Very high in added sugar (36g per glass). Treat as an occasional celebration beverage, or ask for "kurang manis" with extra ice.',
    ordering_tips: ['Order "Bandung Kurang Manis"', 'Enjoy as a sweet dessert accompaniment rather than hydration'],
    description: 'Vibrant pink iced drink of floral rose cordial blended with rich evaporated and condensed milk.',
    image_keyword: 'bandung'
  },
  {
    id: 'milo-dinosaur',
    name_en: 'Milo Dinosaur',
    name_local: '美禄恐龙 (Milo Dinosaur)',
    aliases: ['milo dinosaur', 'milo dino', 'iced milo with powder'],
    category: 'Drinks',
    stall_type: 'Mamak / Kopitiam Drink Stall',
    portion_default: '1 tall glass iced chocolate malt drink topped with a heaping mountain of un-dissolved Milo powder',
    portion_grams: 350,
    calories: 340,
    protein_g: 8,
    carbs_g: 52,
    fat_g: 11,
    sodium_mg: 190,
    sugar_g: 38,
    dietary_flags: ['halal', 'vegetarian'],
    healthier_alternative: 'Swap to "Milo-C Kosong" or "Milo Gao Siew Dai" to retain rich malt chocolate flavor without the mountain of sugar (~saves 180 kcal).',
    ordering_tips: ['Ask for "Milo Kosong" or "Milo Gao Siew Dai" for everyday drinking'],
    description: 'Classic cold Milo drink smothered with two generous tablespoons of dry cocoa-malt powder on top.',
    image_keyword: 'milo_dinosaur'
  },
  {
    id: 'lime-juice-calamansi',
    name_en: 'Iced Calamansi Lime Juice',
    name_local: '酸柑水 (Suan Gan Shui)',
    aliases: ['lime juice', 'calamansi juice', 'suan gan'],
    category: 'Drinks',
    stall_type: 'Drink Stall',
    portion_default: '1 cup with preserved sour plum and ice (300ml)',
    portion_grams: 300,
    calories: 120,
    protein_g: 0,
    carbs_g: 30,
    fat_g: 0,
    sodium_mg: 110,
    sugar_g: 27,
    dietary_flags: ['vegan', 'vegetarian'],
    healthier_alternative: 'Ask for "shao tang" (less sugar syrup) and let the preserved sour plum (bo-loi / sour plum) impart flavor without extra sugar.',
    ordering_tips: ['"Shao tang" reduces the sweet syrup pump by half'],
    description: 'Zesty freshly squeezed calamansi limes over ice with a salted sour plum for a lip-smacking thirst quencher.',
    image_keyword: 'lime_juice'
  },
  // ===================== ADDITIONAL HAWKER CLASSICS =====================
  {
    id: 'chilli-crab',
    name_en: 'Singapore Chilli Crab with Fried Mantou (2 pcs)',
    name_local: '辣椒螃蟹 (Chilli Crab)',
    aliases: ['chilli crab', 'chili crab', 'singapore chilli crab'],
    category: 'Chinese',
    stall_type: 'Seafood / Zi Char Stall',
    portion_default: 'Half mud crab in sweet-savory egg chili gravy with 2 fried mantou buns',
    portion_grams: 480,
    calories: 690,
    protein_g: 48,
    carbs_g: 56,
    fat_g: 31,
    sodium_mg: 1680,
    sugar_g: 19,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Mud crab itself is pure, lean high-protein seafood. Opt for steamed mantou instead of deep-fried, and avoid drenching buns in the sweet egg gravy.',
    ordering_tips: ['Choose steamed mantou over fried to save 120 kcal of oil', 'Focus on the crab meat and go light on gravy spooning'],
    description: 'Fresh mud crab stir-fried in a rich, velvety semi-thick sweet and spicy tomato-chilli sauce with ribboned egg.',
    image_keyword: 'chilli_crab'
  },
  {
    id: 'sambal-stingray',
    name_en: 'Sambal Stingray on Banana Leaf',
    name_local: '魔鬼鱼 (Ikan Bakar Sambal)',
    aliases: ['sambal stingray', 'ikan pari', 'bbq stingray'],
    category: 'Malay',
    stall_type: 'BBQ Seafood Stall',
    portion_default: '1 slab charcoal-grilled stingray with chili paste, cincalok, calamansi (300g)',
    portion_grams: 300,
    calories: 420,
    protein_g: 46,
    carbs_g: 12,
    fat_g: 21,
    sodium_mg: 1150,
    sugar_g: 5,
    dietary_flags: ['halal', 'high_protein', 'low_carb'],
    healthier_alternative: 'Exceptionally rich in lean protein (46g) and collagen! Scrape off excess oily sambal paste and squeeze calamansi lime for bold flavor.',
    ordering_tips: ['Scrape aside thick surface oil from sambal', 'Great low-carb, high-protein hawker dinner'],
    description: 'Meaty stingray fin slathered in spicy belacan sambal, wrapped in banana leaf and barbecued over glowing coals.',
    image_keyword: 'sambal_stingray'
  },
  {
    id: 'sambal-kangkong',
    name_en: 'Sambal Kangkong (Water Spinach with Belacan)',
    name_local: '马拉盏空心菜 (Sambal Kangkong)',
    aliases: ['sambal kangkong', 'kangkung belacan', 'stir fry kangkong'],
    category: 'Chinese',
    stall_type: 'Zi Char Stall',
    portion_default: '1 plate wok-fried water spinach with dried shrimp paste and chili',
    portion_grams: 250,
    calories: 190,
    protein_g: 6,
    carbs_g: 14,
    fat_g: 13,
    sodium_mg: 890,
    sugar_g: 3,
    fiber_g: 5,
    dietary_flags: ['healthier_choice'],
    healthier_alternative: 'Excellent source of dietary fiber, lutein, and iron! Request "shao you" (less oil in the wok) to save ~60 kcal.',
    ordering_tips: ['"Shao you" (less oil)', 'Essential vegetable side to balance a hawker meal'],
    description: 'Crisp water spinach stalks and tender leaves tossed over high heat with spicy fermented shrimp belacan and garlic.',
    image_keyword: 'sambal_kangkong'
  },
  {
    id: 'oyster-omelette',
    name_en: 'Fried Oyster Omelette (Orh Luak)',
    name_local: '蚝煎 (Orh Luak)',
    aliases: ['oyster omelette', 'orh luak', 'fried oyster egg'],
    category: 'Chinese',
    stall_type: 'Oyster Omelette Stall',
    portion_default: '1 plate pan-fried tapioca starch batter with eggs, plump fresh oysters, coriander, and sour chili dip',
    portion_grams: 310,
    calories: 590,
    protein_g: 18,
    carbs_g: 46,
    fat_g: 37,
    sodium_mg: 1240,
    sugar_g: 4,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Oysters are high in zinc and iron, but the tapioca starch absorbs substantial cooking oil. Share with friends or order "Duo dan, shao fen" (more egg, less starch).',
    ordering_tips: ['Ask for "Duo dan, shao fen" (more egg, less starch)', 'Share as a side dish rather than eating solo'],
    description: 'Crispy and gooey pan-fried egg and potato-tapioca batter loaded with briny fresh oysters and fresh coriander.',
    image_keyword: 'oyster_omelette'
  },
  {
    id: 'thunder-tea-rice',
    name_en: 'Hakka Thunder Tea Rice (Lei Cha Fan with Brown Rice)',
    name_local: '客家擂茶 (Lei Cha Fan)',
    aliases: ['thunder tea rice', 'lei cha', 'hakka thunder tea', 'lei cha fan'],
    category: 'Chinese',
    stall_type: 'Thunder Tea Stall',
    portion_default: '1 bowl brown rice topped with 6 blanched greens, tofu, preserved radish, roasted peanuts, green herbal tea broth',
    portion_grams: 450,
    calories: 420,
    protein_g: 19,
    carbs_g: 62,
    fat_g: 11,
    sodium_mg: 620,
    sugar_g: 3,
    fiber_g: 9,
    dietary_flags: ['healthier_choice', 'vegetarian', 'vegan', 'high_protein'],
    healthier_alternative: 'One of the ultimate healthiest hawker meals in Singapore! Packed with 9g of dietary fiber, tea catechins, and zero deep-fried ingredients.',
    ordering_tips: ['Choose brown rice option for low glycemic index', 'Drink all the aromatic herbal tea soup for antioxidants'],
    description: 'Hearty bowl of grain rice surrounded by diced long beans, chye sim, mani cai, tofu, and peanuts, served with a vibrant green basil-mint tea broth.',
    image_keyword: 'thunder_tea_rice'
  },
  {
    id: 'kway-chap-set',
    name_en: 'Kway Chap (Braised Platter with Kway Soup)',
    name_local: '粿汁 (Kway Chap)',
    aliases: ['kway chap', 'kueh chap', 'braised kway chap'],
    category: 'Chinese',
    stall_type: 'Kway Chap Stall',
    portion_default: '1 bowl flat rice sheets in herbal broth + 1 plate braised pork belly, tau pok, hard-boiled egg, salted vegetable',
    portion_grams: 480,
    calories: 580,
    protein_g: 31,
    carbs_g: 61,
    fat_g: 22,
    sodium_mg: 1540,
    sugar_g: 4,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Ask for lean braised meat ("shou rou") and braised bean curd (tau kwa) instead of fatty pork belly and intestines; avoid drinking all the braising broth.',
    ordering_tips: ['"Yao shou rou" (want lean pork)', 'Add braised egg and firm tofu for healthy protein'],
    description: 'Broad flat rice sheets in dark herbal soy broth accompanied by a platter of braised meats, hard-boiled eggs, and tofu.',
    image_keyword: 'kway_chap'
  },
  {
    id: 'braised-pork-trotter-rice',
    name_en: 'Braised Pork Trotter Rice',
    name_local: '猪脚饭 (Zhu Jiao Fan)',
    aliases: ['pork trotter rice', 'braised pork trotter', 'zhu jiao fan'],
    category: 'Chinese',
    stall_type: 'Braised Meat Stall',
    portion_default: '1 plate rice with slow-braised pork knuckle, preserved vegetables, and dark gravy',
    portion_grams: 440,
    calories: 710,
    protein_g: 38,
    carbs_g: 65,
    fat_g: 33,
    sodium_mg: 1420,
    sugar_g: 8,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Rich in collagen. Ask for meat with less gelatinous fat layer, and request gravy on the side to reduce sodium intake.',
    ordering_tips: ['Request lean meat portions', 'Pair with blanched greens'],
    description: 'Melt-in-your-mouth slow-braised pork knuckle infused with star anise, cloves, and cinnamon over jasmine rice.',
    image_keyword: 'pork_trotter'
  },
  {
    id: 'ayam-penyet',
    name_en: 'Ayam Penyet (Smashed Fried Chicken with Fiery Sambal & Rice)',
    name_local: 'Ayam Penyet',
    aliases: ['ayam penyet', 'smashed fried chicken', 'penyet'],
    category: 'Malay',
    stall_type: 'Indonesian / Malay Stall',
    portion_default: '1 plate rice, deep-fried smashed bone-in chicken leg, fried tofu, tempeh, cucumber, fiery terasi sambal',
    portion_grams: 480,
    calories: 780,
    protein_g: 41,
    carbs_g: 72,
    fat_g: 37,
    sodium_mg: 1290,
    sugar_g: 5,
    fiber_g: 5,
    dietary_flags: ['halal', 'high_protein'],
    healthier_alternative: 'Strip the deep-fried batter crust from the chicken skin to save ~160 kcal. The fermented tempeh and tofu provide great plant protein and probiotics!',
    ordering_tips: ['Remove heavy crispy fried crumbs (kremes)', 'Eat all the fresh cabbage and cucumber sides'],
    description: 'Crisp Indonesian smashed fried chicken leg served with fragrant rice, golden fried tofu, tempeh, and tongue-numbing shrimp paste sambal.',
    image_keyword: 'ayam_penyet'
  },
  {
    id: 'chappati-chicken-curry',
    name_en: 'Chappati (2 pieces with Yellow Dhal & Chicken Curry)',
    name_local: 'Chappati (2 keping)',
    aliases: ['chappati', 'chapati', 'roti chapati'],
    category: 'Indian',
    stall_type: 'North Indian / Mamak Stall',
    portion_default: '2 dry-toasted whole wheat flatbreads with yellow lentil dhal and lean chicken piece',
    portion_grams: 290,
    calories: 380,
    protein_g: 22,
    carbs_g: 54,
    fat_g: 9,
    sodium_mg: 680,
    sugar_g: 3,
    fiber_g: 7,
    dietary_flags: ['halal', 'healthier_choice', 'high_protein'],
    healthier_alternative: 'The healthiest Indian hawker flatbread! Made with 100% whole wheat flour (atta), cooked dry on a tawa without oil or ghee.',
    ordering_tips: ['Far healthier than Roti Prata (zero ghee in dough)', 'Dip in dhal for soluble lentil fiber'],
    description: 'Soft, unleavened whole wheat flatbreads cooked dry on a cast-iron skillet, paired with nourishing dhal.',
    image_keyword: 'chappati'
  },
  {
    id: 'appam-sweet',
    name_en: 'Appam (Fermented Rice Pancake with Coconut Milk & Orange Sugar)',
    name_local: 'Appam / Hopper',
    aliases: ['appam', 'plain appam', 'egg appam'],
    category: 'Indian',
    stall_type: 'South Indian Stall',
    portion_default: '2 bowl-shaped fermented rice crepes with fresh coconut milk and orange palm sugar',
    portion_grams: 220,
    calories: 280,
    protein_g: 4,
    carbs_g: 52,
    fat_g: 7,
    sodium_mg: 180,
    sugar_g: 14,
    dietary_flags: ['halal', 'vegetarian', 'healthier_choice'],
    healthier_alternative: 'Naturally gluten-free fermented rice and coconut batter with a soft spongy center and paper-thin crisp lace edges. Use only a pinch of orange sugar.',
    ordering_tips: ['Add egg in the center for "Egg Appam" (+6g protein)', 'Go light on the orange palm sugar'],
    description: 'Delicate South Indian bowl-shaped crepes with crispy lacy borders and a pillowy, slightly fermented center.',
    image_keyword: 'appam'
  },
  {
    id: 'chwee-kueh-4pcs',
    name_en: 'Chwee Kueh (Steamed Rice Cakes with Preserved Radish - 4 pcs)',
    name_local: '水粿 (4粒)',
    aliases: ['chwee kueh', 'chwee kway', 'water rice cake'],
    category: 'Chinese',
    stall_type: 'Chwee Kueh Stall',
    portion_default: '4 small steamed rice flour cups topped with fried preserved turnip (cai po) and chili',
    portion_grams: 240,
    calories: 340,
    protein_g: 5,
    carbs_g: 52,
    fat_g: 13,
    sodium_mg: 920,
    sugar_g: 4,
    dietary_flags: ['vegetarian'],
    healthier_alternative: 'The steamed rice cakes themselves are virtually fat-free! The vegetable oil lies in the braised chai po topping. Ask for "shao cai po" (less turnip topping) to cut half the oil.',
    ordering_tips: ['"Shao cai po" (less preserved turnip oil topping)', 'Pair with unsweetened soya bean milk'],
    description: 'Smooth steamed rice flour cups smothered with glistening fragrant preserved radish and fiery sambal chili.',
    image_keyword: 'chwee_kueh'
  },
  {
    id: 'lor-mai-gai',
    name_en: 'Lor Mai Gai (Steamed Glutinous Rice with Chicken)',
    name_local: '糯米鸡 (Luo Mi Ji)',
    aliases: ['lor mai gai', 'glutinous rice chicken', 'dim sum sticky rice'],
    category: 'Dim Sum',
    stall_type: 'Dim Sum / Bao Stall',
    portion_default: '1 round aluminum tin steamed sticky rice with chicken chunks and Chinese mushroom',
    portion_grams: 180,
    calories: 380,
    protein_g: 14,
    carbs_g: 54,
    fat_g: 12,
    sodium_mg: 720,
    sugar_g: 3,
    dietary_flags: ['high_protein'],
    healthier_alternative: 'Glutinous rice has a high glycemic index. Pair with a hot unsweetened black or green tea to aid carbohydrate metabolism.',
    ordering_tips: ['Share with a friend as a dim sum accompaniment'],
    description: 'Aromatic sticky glutinous rice infused with sesame oil, dark soy, and five-spice, wrapped around savory marinated chicken.',
    image_keyword: 'lor_mai_gai'
  },
  {
    id: 'chee-cheong-fun-hk-prawn',
    name_en: 'Hong Kong Style Prawn Chee Cheong Fun',
    name_local: '港式鲜虾肠粉',
    aliases: ['hk chee cheong fun', 'prawn chee cheong fun', 'shrimp rice roll'],
    category: 'Dim Sum',
    stall_type: 'Dim Sum Stall',
    portion_default: '3 delicate steamed rice rolls filled with whole fresh prawns, drizzled with sweet seasoned light soy sauce',
    portion_grams: 220,
    calories: 240,
    protein_g: 13,
    carbs_g: 38,
    fat_g: 4,
    sodium_mg: 780,
    sugar_g: 4,
    dietary_flags: ['healthier_choice', 'high_protein'],
    healthier_alternative: 'Much healthier than local sweet sauce chee cheong fun! Low in fat, provides lean marine protein, and uses light seasoned soy sauce.',
    ordering_tips: ['Top choice for clean dim sum breakfast', 'Ask for chili on the side'],
    description: 'Paper-thin steamed translucent rice rolls enveloping whole crunchy prawns in a fragrant sweetened soy broth.',
    image_keyword: 'hk_chee_cheong_fun'
  },
  {
    id: 'orh-kueh-yam-cake',
    name_en: 'Steamed Yam Cake (Orh Kueh)',
    name_local: '芋头糕 (Yam Cake)',
    aliases: ['yam cake', 'orh kueh', 'taro cake'],
    category: 'Chinese',
    stall_type: 'Dim Sum / Snack Stall',
    portion_default: '1 thick slice steamed taro rice cake topped with fried shallots, spring onions, dried shrimp, sweet sauce',
    portion_grams: 190,
    calories: 260,
    protein_g: 6,
    carbs_g: 44,
    fat_g: 7,
    sodium_mg: 690,
    sugar_g: 6,
    fiber_g: 4,
    dietary_flags: ['healthier_choice'],
    healthier_alternative: 'Steamed version is far healthier than deep-fried yam ring! Rich in potassium and fiber from real yam cubes. Go light on sweet sauce.',
    ordering_tips: ['Avoid dipping excessively in sweet black sauce', 'Add fresh chopped chili for heat'],
    description: 'Traditional savory steamed cake studded with real yam cubes, dried shrimp, and topped with golden fried shallots.',
    image_keyword: 'yam_cake'
  },
  {
    id: 'western-ribeye-steak',
    name_en: 'Hawker Ribeye Steak (with Baked Potato & Salad)',
    name_local: '西餐牛扒 (Ribeye Steak)',
    aliases: ['ribeye steak', 'western steak', 'hawker steak'],
    category: 'Western',
    stall_type: 'Western Food Stall',
    portion_default: '200g grilled ribeye steak with mushroom gravy, baked potato, garden salad',
    portion_grams: 420,
    calories: 680,
    protein_g: 48,
    carbs_g: 32,
    fat_g: 40,
    sodium_mg: 980,
    sugar_g: 4,
    dietary_flags: ['high_protein', 'low_carb'],
    healthier_alternative: 'High protein powerhouse (48g) for muscle building! Swap fries for baked potato or extra salad to reduce trans fats.',
    ordering_tips: ['Choose baked potato over deep-fried fries', 'Trim edge fat strip from the steak'],
    description: 'Seared beef ribeye cooked to medium tenderness, topped with earthy brown mushroom reduction.',
    image_keyword: 'ribeye_steak'
  },
  {
    id: 'kopi-c-kosong',
    name_en: 'Kopi-C Kosong (Coffee with Evaporated Milk, No Sugar)',
    name_local: '咖啡C无糖 (Kopi C Kosong)',
    aliases: ['kopi c kosong', 'kopi-c kosong', 'coffee evaporated milk no sugar'],
    category: 'Drinks',
    stall_type: 'Kopitiam Drink Stall',
    portion_default: '1 cup (220ml)',
    portion_grams: 220,
    calories: 48,
    protein_g: 2,
    carbs_g: 3,
    fat_g: 3,
    sodium_mg: 40,
    sugar_g: 3,
    dietary_flags: ['healthier_choice', 'low_carb', 'vegetarian'],
    healthier_alternative: 'The gold standard creamy coffee with ZERO added sugar! Evaporated milk provides smooth milkiness without condensed sugar spikes.',
    ordering_tips: ['"Kopi-C Kosong" has only naturally occurring milk lactose (~3g) and zero sucrose'],
    description: 'Robust sock-filtered Robusta coffee combined with unsweetened evaporated milk, completely sugar-free.',
    image_keyword: 'kopi_c_kosong'
  },
  {
    id: 'teh-c-siu-dai',
    name_en: 'Teh-C Siu Dai (Ceylon Tea with Evaporated Milk & Less Sugar)',
    name_local: '茶C少甜 (Teh C Siew Dai)',
    aliases: ['teh c siu dai', 'teh-c siew dai', 'tea evaporated milk less sugar'],
    category: 'Drinks',
    stall_type: 'Kopitiam Drink Stall',
    portion_default: '1 cup (220ml)',
    portion_grams: 220,
    calories: 78,
    protein_g: 2,
    carbs_g: 11,
    fat_g: 3,
    sodium_mg: 45,
    sugar_g: 8,
    dietary_flags: ['healthier_choice', 'vegetarian'],
    healthier_alternative: 'Gentle, balanced milk tea with less than 8g sugar, compared to 21g in standard Teh.',
    ordering_tips: ['Saves ~60 kcal and over 12g sugar compared to normal condensed milk Teh'],
    description: 'Fragrant steeped tea smoothed with evaporated milk and lightly sweetened.',
    image_keyword: 'teh_c'
  },
  {
    id: 'michael-jackson-drink',
    name_en: 'Michael Jackson (Soy Milk with Grass Jelly)',
    name_local: '黑白 / 迈克尔杰克逊 (Soya Bean Grass Jelly)',
    aliases: ['michael jackson drink', 'black and white drink', 'soya chin chow'],
    category: 'Drinks',
    stall_type: 'Soya Bean Stall',
    portion_default: '1 large mug fresh soy milk with grass jelly strips (350ml)',
    portion_grams: 350,
    calories: 140,
    protein_g: 6,
    carbs_g: 24,
    fat_g: 2,
    sodium_mg: 35,
    sugar_g: 16,
    fiber_g: 2,
    dietary_flags: ['healthier_choice', 'vegetarian', 'vegan'],
    healthier_alternative: 'Ask for unsweetened soy milk ("mai tang") with grass jelly to slash sugar to only 6g while enjoying plant isoflavones and protein.',
    ordering_tips: ['Ask for "Soya mai tang" (unsweetened soy milk base)', 'Grass jelly offers cooling properties with minimal calories'],
    description: 'Iconic Singapore concoction of fresh white soya bean milk filled with silky black grass jelly shreds.',
    image_keyword: 'michael_jackson_drink'
  },
  {
    id: 'chendol',
    name_en: 'Chendol (Pandan Jelly with Gula Melaka & Coconut Milk)',
    name_local: '煎蕊 (Chendol)',
    aliases: ['chendol', 'cendol', 'nyonya chendol'],
    category: 'Snacks',
    stall_type: 'Dessert Stall',
    portion_default: '1 bowl shaved ice, green pandan rice flour jelly, soft red beans, fresh coconut milk, smoky gula melaka syrup',
    portion_grams: 280,
    calories: 386,
    protein_g: 5,
    carbs_g: 56,
    fat_g: 16,
    sodium_mg: 85,
    sugar_g: 34,
    fiber_g: 4,
    dietary_flags: ['vegetarian'],
    healthier_alternative: 'Ask for "shao gula melaka" (less palm sugar syrup) and less coconut milk to reduce calories by ~130 kcal. Red beans provide good dietary fiber.',
    ordering_tips: ['"Shao gula melaka" (less syrup)', 'Share with a dining partner after a meal'],
    description: 'Fragrant shaved ice dessert brimming with bright green pandan jelly strands, sweet red beans, creamy coconut milk, and smoky palm sugar.',
    image_keyword: 'chendol'
  },
  {
    id: 'ice-kachang',
    name_en: 'Ice Kachang (Singapore Shaved Ice Mountain)',
    name_local: '红豆冰 (Ice Kachang)',
    aliases: ['ice kachang', 'ais kacang', 'red bean ice'],
    category: 'Snacks',
    stall_type: 'Dessert Stall',
    portion_default: '1 tall mound shaved ice drenched in rose, sarsi, and pandan syrups, evaporated milk, topped with sweet corn, attap chee, red beans, grass jelly',
    portion_grams: 350,
    calories: 290,
    protein_g: 5,
    carbs_g: 64,
    fat_g: 2,
    sodium_mg: 70,
    sugar_g: 46,
    fiber_g: 5,
    dietary_flags: ['vegetarian'],
    healthier_alternative: 'Low in fat, but very high in sugar syrups (~46g). Ask for "shao tang" (less colored syrup) or share with 2-3 friends on a hot afternoon.',
    ordering_tips: ['Request less syrup on top', 'Enjoy the palm seeds (attap chee) and red beans underneath'],
    description: 'Spectacular rainbow dome of finely shaved ice concealing sweet treasures like attap seeds, sweet red beans, grass jelly, and creamed corn.',
    image_keyword: 'ice_kachang'
  },
  {
    id: 'plain-water',
    name_en: 'Plain Water',
    name_local: '白开水 / 冰水 (Plain / Ice Water)',
    aliases: ['water', 'plain water', 'ice water', 'mineral water', 'warm water', 'bottled water', 'drinking water'],
    category: 'Drinks',
    stall_type: 'Drink Stall',
    portion_default: '1 glass / bottle (~300ml - 500ml)',
    portion_grams: 300,
    calories: 0,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 0,
    sodium_mg: 0,
    sugar_g: 0,
    dietary_flags: ['healthier_choice'],
    healthier_alternative: 'Pure 0-calorie hydration. The healthiest drink option at any hawker center!',
    ordering_tips: ['Ask for "Pai Kwee" (warm water) or "Peng Kwee" (iced water)'],
    description: 'Pure refreshing water with zero calories, zero sugar, and zero fat.',
    image_keyword: 'plain_water'
  }
];

export function getDishesByCategory(category?: string): HawkerDish[] {
  if (!category || category === 'All') return HAWKER_DISHES;
  return HAWKER_DISHES.filter(d => d.category.toLowerCase() === category.toLowerCase());
}

export function searchDishes(query: string): HawkerDish[] {
  const q = query.toLowerCase().trim();
  if (!q) return HAWKER_DISHES;
  return HAWKER_DISHES.filter(d => 
    d.name_en.toLowerCase().includes(q) ||
    d.name_local.toLowerCase().includes(q) ||
    d.aliases.some(a => a.toLowerCase().includes(q)) ||
    d.category.toLowerCase().includes(q) ||
    d.stall_type.toLowerCase().includes(q)
  );
}

export function getDishById(id: string): HawkerDish | undefined {
  return HAWKER_DISHES.find(d => d.id === id);
}
